### ISSUE TITLE
No commands gist:list and others of this plugin

### ISSUE THREAD

**Issue by Alex-Space** [aki77/atom-gist#20]
I pasted a token to settings and tried to find any command of this plugin though CTRL+SHIFT+P. There are no commands. I restarted Atom and still have the same problem. How to make it works?
![gist](https://cloud.githubusercontent.com/assets/7780469/17508273/d8f3a922-5e1c-11e6-8226-81b579e08daa.png)
![gist2](https://cloud.githubusercontent.com/assets/7780469/17508293/f5ac7c60-5e1c-11e6-82a0-4ee7b72b0231.png)

**Comment by firemiles** [comment]
@Alex-Space I think you can call the command at other tab，not setting tab， that works。

**Comment by 1activegeek** [comment]
I've had the same issue. Inconsistent accessibility of the plugin is causing it to not be useful. It seems to be the only one I've found that will let me open/edit existing gists, but when it doesn't actually load, it's not really bringing ANY value anymore.

**Comment by dafcarte** [comment]
Doesn't appear that the author is interested in supporting it. I'd look elsewhere for a better plugin. I just uninstalled it myself because of this issue.

**Comment by 1activegeek** [comment]
Actually if anyone has the same issue as I, I think I finally understand the issue. Weird requirement I think, but I was able to get the Gist option to show in the command palette consistently. The issue was, it will only appear when there is an open document in the editor. My problem was I kept opening the editor fresh with no new document or anything, and it wouldn't show. As soon as I hit CMD+N for a new doc/file, then tried - it works consistently. And you have to actually be "in focus" on the doc, not a different tab like the Settings where I often tried to launch it from.

**Comment by aki77** [comment]
It works only within atom-text-editor.

**Comment by aki77** [comment]
#18
